Spring boot Security Basics
dmytro-voronin/jv-book-store pull request #7
Opened 2023-12-05 13:08 UTC by dmytro-voronin

2023-12-05 19:21 UTC, Sanderfuck requested changes

2023-12-05 19:21 UTC, Sanderfuck commented on src/main/java/mate/academy/bookstore/dto/user/UserRegistrationRequest.java
> +    private String lastName;
One letter of firstname and lastname not looks like in real life

2023-12-05 19:21 UTC, Sanderfuck commented on src/main/java/mate/academy/bookstore/exception/CustomGlobalExceptionHandler.java
> +        body.put("message", ex.getMessage());
You can save this strings in constants

2023-12-07 10:06 UTC, kozhukhovsky approved these changes

2023-12-07 10:06 UTC, kozhukhovsky commented on src/main/java/mate/academy/bookstore/dto/user/UserRegistrationRequest.java
> +
```suggestion
```

2024-02-22 08:58 UTC, closed without merging