Spring boot security
dmytro-voronin/jv-book-store pull request #8
Opened 2023-12-08 18:10 UTC by dmytro-voronin

2023-12-09 10:48 UTC, olekskov requested changes

2023-12-09 10:48 UTC, olekskov commented on src/main/java/mate/academy/bookstore/service/user/impl/UserServiceImpl.java
>          return userMapper.toDto(userRepository.save(user));
I cannot see you set any role to user during registration. Thus I don't think new user may access required endpoints

2023-12-12 13:03 UTC, okuzan requested changes

2023-12-12 13:03 UTC, okuzan commented on src/main/java/mate/academy/bookstore/config/SecurityConfig.java
> +
```suggestion
public class SecurityConfig {
```

2023-12-12 13:03 UTC, okuzan commented on src/main/java/mate/academy/bookstore/model/Role.java
> +
```suggestion
```

2023-12-12 13:03 UTC, okuzan commented on src/main/java/mate/academy/bookstore/service/role/impl/RoleServiceImpl.java
> +                new RuntimeException("can't find role by roleName: " + roleName));
EntityNotFoundException

2023-12-12 13:03 UTC, okuzan commented on src/main/resources/db/changelog/changes/03-create-roles-table.yaml
> +                    unique: true
make sure each file ends with exactly one empty line
![image](https://github.com/dmytro-voronin/jv-book-store/assets/49767049/f438a5ec-b62b-4474-9b30-fc6cbbc77bf8)

2023-12-12 13:03 UTC, okuzan commented on src/main/resources/db/changelog/changes/06-insert-users-table.yml
> +              - column: {name: password, value: "$2a$10$1pEimxSACCZhIfEYS12Bze6VtLuJYWAHCZUwLb.r9P2barlIgae5a"}
add comment with this password in plaintext for testing purposes

2023-12-12 16:46 UTC, okuzan approved these changes

2023-12-12 16:46 UTC, okuzan commented on src/main/java/mate/academy/bookstore/controller/BookController.java
> +    @PreAuthorize("hasRole('USER')")
It wasn't clarified in the task description, but let's allow Admins to do user roles too, for that, you need to remove @PreAuthorize("hasRole('USER')") and leave only @PreAuthorize("hasRole('ADMIN')") - others are secured in SecurityConfig

2024-02-22 08:59 UTC, closed without merging